name = "Zernike"
uuid = "e14b762e-e195-443f-a1b1-09f2ab0cc6c8"
authors = ["Sagnac"]
version = "5.1.0"

[deps]
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ShiftedArrays = "1277b4bf-5013-50f5-be3d-901d8477a67a"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[targets]
test = ["Test", "StatsBase"]

[compat]
julia = "1.10"
LinearAlgebra = "1.10"
Printf = "1.10"
ShiftedArrays = "2.0.0"
GLMakie = "0.10.0"
